#!/bin/bash

set -e

# Set number of processes and threads
NUM_PROCESSES=1
NUM_THREADS=4
NUM_PARTICLES=$(expr $MPI_PROCESSES \* $OMP_NUM_THREADS \* 10000)

# Set executable and cross section
EXE="$(pwd)/openmc/build/bin/openmc -n $NUM_PARTICLES -s $NUM_THREADS"
export CROSS_SECTIONS=$(pwd)/openmc/data/nndc/cross_sections.xml

# Run tests
for testname in small-notallies small-tallies large-notallies large-tallies; do
    echo Running $testname
    cd $testname
    mpiexec -n $NUM_PROCESSES $EXE > stdout 2>&1
    cd ..
done
